name: Run Tests

on:
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: sudo apt-get install curl jq socat make
    - name: Run the test suite
      run: make test
